# Generated by Django 2.0.6 on 2019-05-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_foo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text1',
            new_name='answer1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='foo',
        ),
        migrations.AddField(
            model_name='post',
            name='answer2',
            field=models.TextField(null=True),
        ),
    ]
