# Generated by Django 2.0.6 on 2019-05-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text1',
            field=models.TextField(null=True),
        ),
    ]
