# Generated by Django 2.0.6 on 2019-08-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190808_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sampleId',
        ),
        migrations.AddField(
            model_name='post',
            name='answer3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
