# Generated by Django 2.0.6 on 2019-08-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190808_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answer3',
        ),
    ]
